service: tech-in-srilanka # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  role: arn:aws:iam::649854575814:role/yalk-bot-lambda-role
  environment:
    BUFFER_ACCESS_TOKEN: ${file(./env.yml):prod.bufferAccessToken}
    BUFFER_FACEBOOK_ID: ${file(./env.yml):prod.bufferFacebookId}
    BUFFER_LINKEDIN_ID: ${file(./env.yml):prod.bufferLinkedinId}

functions:
  publish:
    handler: handler.publish
    # timeout: 10
    # events:
    #   - schedule: rate(1 hour)
